services:
  - type: web
    name: pdflix
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
